import pandas as pd
df= pd.read_csv("train.csv")
print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.duplicated().sum())
print(df.columns)
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])
print(df["Cabin"].isnull().sum())
df["Cabinknown"]=df["Cabin"].notna().astype(int)
print(df["Cabinknown"].value_counts())
print(df["Survived"].value_counts())
survival_rate=df["Survived"].mean()*100
print(f"overall survival rate: {survival_rate:.2f}%")
print(df.groupby("Sex")["Survived"].mean().mul(100).round(2))
